# Generated by Django 3.2 on 2021-04-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_comment_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
