# Generated by Django 3.2 on 2021-04-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_comment_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
